package WEC::MySQL::Constants;
use 5.008;
use strict;
use warnings;

use Exporter::Tidy
    Capabilities=> [qw(LONG_PASSWORD FOUND_ROWS LONG_FLAG CONNECT_WITH_DB 
                       NO_SCHEMA COMPRESS ODBC LOCAL_FILES IGNORE_SPACE 
                       CAN_CHANGE_USER INTERACTIVE SSL IGNORE_SIGPIPE 
                       TRANSACTIONS)],
    Commands	=> [qw(SLEEP QUIT INIT_DB QUERY FIELD_LIST CREATE_DB DROP_DB 
                       REFRESH SHUTDOWN STATISTICS PROCESS_INFO CONNECT 
                       PROCESS_KILL DEBUG PING TIME DELAYED_INSERT CHANGE_USER 
                       BINLOG_DUMP TABLE_DUMP CONNECT_OUT)],
    Refresh	=> [qw(REFRESH_GRANT REFRESH_LOG REFRESH_TABLES REFRESH_HOSTS 
                       REFRESH_STATUS REFRESH_THREADS REFRESH_SLAVE 
                       REFRESH_MASTER REFRESH_READ_LOCK REFRESH_FAST 
                       REFRESH_QUERY_CACHE REFRESH_QUERY_CACHE_FREE 
                       REFRESH_DES_KEY_FILE REFRESH_USER_RESOURCES)],
    Charsets	=> [qw(BIG5 CZECH DEC8 DOS GERMAN1 HP8 KOI8_RU LATIN1 LATIN2 
                       SWE7 USA7 UJIS SJIS CP1251 DANISH HEBREW WIN1251 TIS620 
                       EUC_KR ESTONIA HUNGARIAN KOI8_UKR WIN1251UKR GB2312 
                       GREEK WIN1250 CROAT GBK CP1257 LATIN5 LATIN1_DE)],
    FieldTypes	=> [qw( DECIMAL TINY SHORT LONG FLOAT DOUBLE NULL TIMESTAMP 
                        LONGLONG INT24 DATE TIME DATETIME YEAR NEWDATE ENUM SET
                        TINY_BLOB MEDIUM_BLOB LONG_BLOB BLOB VAR_STRING STRING 
                        GEOMETRY)],
    Errors	=> [qw(HASHCHK NISAMCHK NO YES CANT_CREATE_FILE 
                       CANT_CREATE_TABLE CANT_CREATE_DB DB_CREATE_EXISTS 
                       DB_DROP_EXISTS DB_DROP_DELETE DB_DROP_RMDIR 
                       CANT_DELETE_FILE CANT_FIND_SYSTEM_REC CANT_GET_STAT 
                       CANT_GET_WD CANT_LOCK CANT_OPEN_FILE FILE_NOT_FOUND 
                       CANT_READ_DIR CANT_SET_WD CHECKREAD DISK_FULL DUP_KEY 
                       ERROR_ON_CLOSE ERROR_ON_READ ERROR_ON_RENAME 
                       ERROR_ON_WRITE FILE_USED FILSORT_ABORT FORM_NOT_FOUND 
                       GET_ERRNO ILLEGAL_HA KEY_NOT_FOUND NOT_FORM_FILE 
                       NOT_KEYFILE OLD_KEYFILE OPEN_AS_READONLY OUTOFMEMORY 
                       OUT_OF_SORTMEMORY UNEXPECTED_EOF CON_COUNT_ERROR 
                       OUT_OF_RESOURCES BAD_HOST_ERROR HANDSHAKE_ERROR 
                       DBACCESS_DENIED_ERROR ACCESS_DENIED_ERROR NO_DB_ERROR 
                       UNKNOWN_COM_ERROR BAD_NULL_ERROR BAD_DB_ERROR 
                       TABLE_EXISTS_ERROR BAD_TABLE_ERROR NON_UNIQ_ERROR 
                       SERVER_SHUTDOWN BAD_FIELD_ERROR WRONG_FIELD_WITH_GROUP 
                       WRONG_GROUP_FIELD WRONG_SUM_SELECT WRONG_VALUE_COUNT 
                       TOO_LONG_IDENT DUP_FIELDNAME DUP_KEYNAME DUP_ENTRY 
                       WRONG_FIELD_SPEC PARSE_ERROR EMPTY_QUERY NONUNIQ_TABLE 
                       INVALID_DEFAULT MULTIPLE_PRI_KEY TOO_MANY_KEYS 
                       TOO_MANY_KEY_PARTS TOO_LONG_KEY 
                       KEY_COLUMN_DOES_NOT_EXITS BLOB_USED_AS_KEY 
                       TOO_BIG_FIELDLENGTH WRONG_AUTO_KEY READY NORMAL_SHUTDOWN
                       GOT_SIGNAL SHUTDOWN_COMPLETE FORCING_CLOSE IPSOCK_ERROR 
                       NO_SUCH_INDEX WRONG_FIELD_TERMINATORS 
                       BLOBS_AND_NO_TERMINATED TEXTFILE_NOT_READABLE 
                       FILE_EXISTS_ERROR LOAD_INFO ALTER_INFO WRONG_SUB_KEY 
                       CANT_REMOVE_ALL_FIELDS CANT_DROP_FIELD_OR_KEY 
                       INSERT_INFO INSERT_TABLE_USED NO_SUCH_THREAD 
                       KILL_DENIED_ERROR NO_TABLES_USED TOO_BIG_SET 
                       NO_UNIQUE_LOGFILE TABLE_NOT_LOCKED_FOR_WRITE 
                       TABLE_NOT_LOCKED BLOB_CANT_HAVE_DEFAULT WRONG_DB_NAME 
                       WRONG_TABLE_NAME TOO_BIG_SELECT UNKNOWN_ERROR 
                       UNKNOWN_PROCEDURE WRONG_PARAMCOUNT_TO_PROCEDURE 
                       WRONG_PARAMETERS_TO_PROCEDURE UNKNOWN_TABLE 
                       FIELD_SPECIFIED_TWICE INVALID_GROUP_FUNC_USE 
                       UNSUPPORTED_EXTENSION TABLE_MUST_HAVE_COLUMNS 
                       RECORD_FILE_FULL UNKNOWN_CHARACTER_SET TOO_MANY_TABLES 
                       TOO_MANY_FIELDS TOO_BIG_ROWSIZE STACK_OVERRUN 
                       WRONG_OUTER_JOIN NULL_COLUMN_IN_INDEX CANT_FIND_UDF 
                       CANT_INITIALIZE_UDF UDF_NO_PATHS UDF_EXISTS 
                       CANT_OPEN_LIBRARY CANT_FIND_DL_ENTRY 
                       FUNCTION_NOT_DEFINED HOST_IS_BLOCKED HOST_NOT_PRIVILEGED
                       PASSWORD_ANONYMOUS_USER PASSWORD_NOT_ALLOWED 
                       PASSWORD_NO_MATCH UPDATE_INFO CANT_CREATE_THREAD 
                       WRONG_VALUE_COUNT_ON_ROW CANT_REOPEN_TABLE 
                       INVALID_USE_OF_NULL REGEXP_ERROR 
                       MIX_OF_GROUP_FUNC_AND_FIELDS NONEXISTING_GRANT 
                       TABLEACCESS_DENIED_ERROR COLUMNACCESS_DENIED_ERROR 
                       ILLEGAL_GRANT_FOR_TABLE GRANT_WRONG_HOST_OR_USER 
                       NO_SUCH_TABLE NONEXISTING_TABLE_GRANT 
                       NOT_ALLOWED_COMMAND SYNTAX_ERROR 
                       DELAYED_CANT_CHANGE_LOCK TOO_MANY_DELAYED_THREADS
                       ABORTING_CONNECTION NET_PACKET_TOO_LARGE 
                       NET_READ_ERROR_FROM_PIPE NET_FCNTL_ERROR 
                       NET_PACKETS_OUT_OF_ORDER NET_UNCOMPRESS_ERROR 
                       NET_READ_ERROR NET_READ_INTERRUPTED NET_ERROR_ON_WRITE 
                       NET_WRITE_INTERRUPTED TOO_LONG_STRING 
                       TABLE_CANT_HANDLE_BLOB TABLE_CANT_HANDLE_AUTO_INCREMENT 
                       DELAYED_INSERT_TABLE_LOCKED WRONG_COLUMN_NAME 
                       WRONG_KEY_COLUMN WRONG_MRG_TABLE DUP_UNIQUE 
                       BLOB_KEY_WITHOUT_LENGTH PRIMARY_CANT_HAVE_NULL 
                       TOO_MANY_ROWS REQUIRES_PRIMARY_KEY NO_RAID_COMPILED 
                       UPDATE_WITHOUT_KEY_IN_SAFE_MODE KEY_DOES_NOT_EXITS 
                       CHECK_NO_SUCH_TABLE CHECK_NOT_IMPLEMENTED 
                       CANT_DO_THIS_DURING_AN_TRANSACTION ERROR_DURING_COMMIT 
                       ERROR_DURING_ROLLBACK ERROR_DURING_FLUSH_LOGS 
                       ERROR_DURING_CHECKPOINT NEW_ABORTING_CONNECTION 
                       DUMP_NOT_IMPLEMENTED FLUSH_MASTER_BINLOG_CLOSED 
                       INDEX_REBUILD MASTER MASTER_NET_READ MASTER_NET_WRITE 
                       FT_MATCHING_KEY_NOT_FOUND LOCK_OR_ACTIVE_TRANSACTION 
                       UNKNOWN_SYSTEM_VARIABLE CRASHED_ON_USAGE 
                       CRASHED_ON_REPAIR WARNING_NOT_COMPLETE_ROLLBACK 
                       TRANS_CACHE_FULL SLAVE_MUST_STOP SLAVE_NOT_RUNNING 
                       BAD_SLAVE MASTER_INFO SLAVE_THREAD 
                       TOO_MANY_USER_CONNECTIONS 
                       SET_CONSTANTS_ONLY LOCK_WAIT_TIMEOUT LOCK_TABLE_FULL 
                       READ_ONLY_TRANSACTION DROP_DB_WITH_READ_LOCK 
                       CREATE_DB_WITH_READ_LOCK WRONG_ARGUMENTS 
                       NO_PERMISSION_TO_CREATE_USER UNION_TABLES_IN_DIFFERENT_DIR 
                       LOCK_DEADLOCK TABLE_CANT_HANDLE_FULLTEXT 
                       CANNOT_ADD_FOREIGN NO_REFERENCED_ROW ROW_IS_REFERENCED 
                       CONNECT_TO_MASTER QUERY_ON_MASTER 
                       ERROR_WHEN_EXECUTING_COMMAND WRONG_USAGE 
                       WRONG_NUMBER_OF_COLUMNS_IN_SELECT 
                       CANT_UPDATE_WITH_READLOCK MIXING_NOT_ALLOWED 
                       DUP_ARGUMENT USER_LIMIT_REACHED 
                       SPECIFIC_ACCESS_DENIED_ERROR LOCAL_VARIABLE 
                       GLOBAL_VARIABLE NO_DEFAULT WRONG_VALUE_FOR_VAR 
                       WRONG_TYPE_FOR_VAR VAR_CANT_BE_READ 
                       CANT_USE_OPTION_HERE NOT_SUPPORTED_YET 
                       MASTER_FATAL_ERROR_READING_BINLOG 
                       SLAVE_IGNORED_TABLE INCORRECT_GLOBAL_LOCAL_VAR 
                       ERROR_MESSAGES)],
    other	=> [qw(BIN_LOG_HEADER_SIZE PORT SOCKET PART_MASK
                       REC_LEN COMPRESS_LEN MAX3
                       ENCODED_NULL ENCODED_ZERO ENCODED_ERROR)];


use constant {
    # Capabilities
    LONG_PASSWORD	=> 1,		# New more secure passwords
    FOUND_ROWS		=> 2,		# Found instead of affected rows
    LONG_FLAG		=> 4,		# Get all column flags
    CONNECT_WITH_DB	=> 8,		# One can specify db on connect
    NO_SCHEMA		=> 16,		# Don't allow database.table.column
    COMPRESS		=> 32,		# Can use compression protocol
    ODBC		=> 64,		# ODBC client
    LOCAL_FILES		=> 128,		# Can use LOAD DATA LOCAL
    IGNORE_SPACE	=> 256,		# Ignore spaces before '('
    CAN_CHANGE_USER	=> 512,		# Support the mysql_change_user()
    INTERACTIVE		=> 1024,	# This is an interactive client
    SSL			=> 2048,	# Switch to SSL after handshake
    IGNORE_SIGPIPE	=> 4096,	# IGNORE sigpipes
    TRANSACTIONS	=> 8192,	# Client knows about transactions

    # Commands		  Argument	Allowed from client
    SLEEP	=> 0,	#		No
    QUIT	=> 1,	# ""
    INIT_DB	=> 2,	# db
    QUERY	=> 3,	# query
    FIELD_LIST	=> 4,	# table, wild
    CREATE_DB	=> 5,	# db
    DROP_DB	=> 6,	# db
    REFRESH	=> 7,	# option bits
    SHUTDOWN	=> 8,	#
    STATISTICS	=> 9,	#
    PROCESS_INFO=> 10,	#
    CONNECT	=> 11,	#		No
    PROCESS_KILL=> 12,	# 4-byte pid
    DEBUG	=> 13,	#
    PING	=> 14,	#
    TIME	=> 15,	#		No
    DELAYED_INSERT => 16,	#	No
    CHANGE_USER	=> 17,	# user,pass,db
    BINLOG_DUMP	=> 18,	# pos,flags,id,filename
    TABLE_DUMP	=> 19,	# db,table
    CONNECT_OUT	=> 20,	#		No
    PART_MASK	=> 32,

    # Refresh bits
    REFRESH_GRANT	=> 1,	# Refresh grant tables
    REFRESH_LOG		=> 2,	# Start on new log file
    REFRESH_TABLES	=> 4,	# close all tables
    REFRESH_HOSTS	=> 8,	# Flush host cache
    REFRESH_STATUS	=> 16,	# Flush status variables
    REFRESH_THREADS	=> 32,	# Flush thread cache
    REFRESH_SLAVE	=> 64,	# Reset master info and restart slave thread
    REFRESH_MASTER	=> 128,	# Remove all bin logs in the index and truncate the index

    # The following can't be set with mysql_refresh()
    REFRESH_READ_LOCK	=> 16384,	# Lock tables for read
    REFRESH_FAST	=> 32768,	# Intern flag

    # RESET (remove all queries) from query cache
    REFRESH_QUERY_CACHE	=> 65536,
    REFRESH_QUERY_CACHE_FREE	=> 0x20000,	# pack query cache
    REFRESH_DES_KEY_FILE	=> 0x40000,
    REFRESH_USER_RESOURCES	=> 0x80000,

    BIN_LOG_HEADER_SIZE	=> 4,
    # Default port
    PORT	=> 3306,
    # Default socket (on my system)
    SOCKET	=> "unix:///var/run/mysqld/mysqld.sock",

    REC_LEN		=> 4,
    COMPRESS_LEN	=> 7,

    ENCODED_NULL	=> pack("C", 251),
    ENCODED_ZERO 	=> pack("C", 0),
    ENCODED_ERROR 	=> pack("C", 255),

    # Maximum value representable with 3 bytes
    MAX3		=> 2**24-1,

    # From include/mysql_com.h
    DECIMAL	=>   0,
    TINY	=>   1,
    SHORT	=>   2,
    LONG	=>   3,
    FLOAT	=>   4,
    DOUBLE	=>   5,
    NULL	=>   6,
    TIMESTAMP	=>   7,
    LONGLONG	=>   8,
    INT24	=>   9,
    DATE	=>  10,
    TIME	=>  11,
    DATETIME	=>  12,
    YEAR	=>  13,
    NEWDATE	=>  14,
    ENUM	=> 247,
    SET		=> 248,
    TINY_BLOB	=> 249,
    MEDIUM_BLOB	=> 250,
    LONG_BLOB	=> 251,
    BLOB	=> 252,
    VAR_STRING	=> 253,
    STRING	=> 254,
    GEOMETRY	=> 255,

    # From sql/share/charsets/Index in mysql-4.0.20
    BIG5	=>  1,
    CZECH	=>  2,
    DEC8	=>  3,
    DOS		=>  4,
    GERMAN1	=>  5,
    HP8		=>  6,
    KOI8_RU	=>  7,
    LATIN1	=>  8,
    LATIN2	=>  9,
    SWE7	=> 10,
    USA7	=> 11,
    UJIS	=> 12,
    SJIS	=> 13,
    CP1251	=> 14,
    DANISH	=> 15,
    HEBREW	=> 16,
    # The win1251 character set is deprecated.  Please use cp1251 instead.
    WIN1251	=> 17,
    TIS620	=> 18,
    EUC_KR	=> 19,
    ESTONIA	=> 20,
    HUNGARIAN	=> 21,
    KOI8_UKR	=> 22,
    WIN1251UKR	=> 23,
    GB2312	=> 24,
    GREEK	=> 25,
    WIN1250	=> 26,
    CROAT	=> 27,
    GBK		=> 28,
    CP1257	=> 29,
    LATIN5	=> 30,
    LATIN1_DE	=> 31,

    # From include/mysqld_error.h in mysql-4.0.20
    HASHCHK			=> 1000,
    NISAMCHK			=> 1001,
    NO				=> 1002,
    YES				=> 1003,
    CANT_CREATE_FILE		=> 1004,
    CANT_CREATE_TABLE		=> 1005,
    CANT_CREATE_DB		=> 1006,
    DB_CREATE_EXISTS		=> 1007,
    DB_DROP_EXISTS		=> 1008,
    DB_DROP_DELETE		=> 1009,
    DB_DROP_RMDIR		=> 1010,
    CANT_DELETE_FILE		=> 1011,
    CANT_FIND_SYSTEM_REC	=> 1012,
    CANT_GET_STAT		=> 1013,
    CANT_GET_WD			=> 1014,
    CANT_LOCK			=> 1015,
    CANT_OPEN_FILE		=> 1016,
    FILE_NOT_FOUND		=> 1017,
    CANT_READ_DIR		=> 1018,
    CANT_SET_WD			=> 1019,
    CHECKREAD			=> 1020,
    DISK_FULL			=> 1021,
    DUP_KEY			=> 1022,
    ERROR_ON_CLOSE		=> 1023,
    ERROR_ON_READ		=> 1024,
    ERROR_ON_RENAME		=> 1025,
    ERROR_ON_WRITE		=> 1026,
    FILE_USED			=> 1027,
    FILSORT_ABORT		=> 1028,
    FORM_NOT_FOUND		=> 1029,
    GET_ERRNO			=> 1030,
    ILLEGAL_HA			=> 1031,
    KEY_NOT_FOUND		=> 1032,
    NOT_FORM_FILE		=> 1033,
    NOT_KEYFILE			=> 1034,
    OLD_KEYFILE			=> 1035,
    OPEN_AS_READONLY		=> 1036,
    OUTOFMEMORY			=> 1037,
    OUT_OF_SORTMEMORY		=> 1038,
    UNEXPECTED_EOF		=> 1039,
    CON_COUNT_ERROR		=> 1040,
    OUT_OF_RESOURCES		=> 1041,
    BAD_HOST_ERROR		=> 1042,
    HANDSHAKE_ERROR		=> 1043,
    DBACCESS_DENIED_ERROR	=> 1044,
    ACCESS_DENIED_ERROR		=> 1045,
    NO_DB_ERROR			=> 1046,
    UNKNOWN_COM_ERROR		=> 1047,
    BAD_NULL_ERROR		=> 1048,
    BAD_DB_ERROR		=> 1049,
    TABLE_EXISTS_ERROR		=> 1050,
    BAD_TABLE_ERROR		=> 1051,
    NON_UNIQ_ERROR		=> 1052,
    SERVER_SHUTDOWN		=> 1053,
    BAD_FIELD_ERROR		=> 1054,
    WRONG_FIELD_WITH_GROUP	=> 1055,
    WRONG_GROUP_FIELD		=> 1056,
    WRONG_SUM_SELECT		=> 1057,
    WRONG_VALUE_COUNT		=> 1058,
    TOO_LONG_IDENT		=> 1059,
    DUP_FIELDNAME		=> 1060,
    DUP_KEYNAME			=> 1061,
    DUP_ENTRY			=> 1062,
    WRONG_FIELD_SPEC		=> 1063,
    PARSE_ERROR			=> 1064,
    EMPTY_QUERY			=> 1065,
    NONUNIQ_TABLE		=> 1066,
    INVALID_DEFAULT		=> 1067,
    MULTIPLE_PRI_KEY		=> 1068,
    TOO_MANY_KEYS		=> 1069,
    TOO_MANY_KEY_PARTS		=> 1070,
    TOO_LONG_KEY		=> 1071,
    KEY_COLUMN_DOES_NOT_EXITS	=> 1072,
    BLOB_USED_AS_KEY		=> 1073,
    TOO_BIG_FIELDLENGTH		=> 1074,
    WRONG_AUTO_KEY		=> 1075,
    READY			=> 1076,
    NORMAL_SHUTDOWN		=> 1077,
    GOT_SIGNAL			=> 1078,
    SHUTDOWN_COMPLETE		=> 1079,
    FORCING_CLOSE		=> 1080,
    IPSOCK_ERROR		=> 1081,
    NO_SUCH_INDEX		=> 1082,
    WRONG_FIELD_TERMINATORS	=> 1083,
    BLOBS_AND_NO_TERMINATED	=> 1084,
    TEXTFILE_NOT_READABLE	=> 1085,
    FILE_EXISTS_ERROR		=> 1086,
    LOAD_INFO			=> 1087,
    ALTER_INFO			=> 1088,
    WRONG_SUB_KEY		=> 1089,
    CANT_REMOVE_ALL_FIELDS	=> 1090,
    CANT_DROP_FIELD_OR_KEY	=> 1091,
    INSERT_INFO			=> 1092,
    INSERT_TABLE_USED		=> 1093,
    NO_SUCH_THREAD		=> 1094,
    KILL_DENIED_ERROR		=> 1095,
    NO_TABLES_USED		=> 1096,
    TOO_BIG_SET			=> 1097,
    NO_UNIQUE_LOGFILE		=> 1098,
    TABLE_NOT_LOCKED_FOR_WRITE	=> 1099,
    TABLE_NOT_LOCKED		=> 1100,
    BLOB_CANT_HAVE_DEFAULT	=> 1101,
    WRONG_DB_NAME		=> 1102,
    WRONG_TABLE_NAME		=> 1103,
    TOO_BIG_SELECT		=> 1104,
    UNKNOWN_ERROR		=> 1105,
    UNKNOWN_PROCEDURE		=> 1106,
    WRONG_PARAMCOUNT_TO_PROCEDURE	=> 1107,
    WRONG_PARAMETERS_TO_PROCEDURE	=> 1108,
    UNKNOWN_TABLE		=> 1109,
    FIELD_SPECIFIED_TWICE	=> 1110,
    INVALID_GROUP_FUNC_USE	=> 1111,
    UNSUPPORTED_EXTENSION	=> 1112,
    TABLE_MUST_HAVE_COLUMNS	=> 1113,
    RECORD_FILE_FULL		=> 1114,
    UNKNOWN_CHARACTER_SET	=> 1115,
    TOO_MANY_TABLES		=> 1116,
    TOO_MANY_FIELDS		=> 1117,
    TOO_BIG_ROWSIZE		=> 1118,
    STACK_OVERRUN		=> 1119,
    WRONG_OUTER_JOIN		=> 1120,
    NULL_COLUMN_IN_INDEX	=> 1121,
    CANT_FIND_UDF		=> 1122,
    CANT_INITIALIZE_UDF		=> 1123,
    UDF_NO_PATHS		=> 1124,
    UDF_EXISTS			=> 1125,
    CANT_OPEN_LIBRARY		=> 1126,
    CANT_FIND_DL_ENTRY		=> 1127,
    FUNCTION_NOT_DEFINED	=> 1128,
    HOST_IS_BLOCKED		=> 1129,
    HOST_NOT_PRIVILEGED		=> 1130,
    PASSWORD_ANONYMOUS_USER	=> 1131,
    PASSWORD_NOT_ALLOWED	=> 1132,
    PASSWORD_NO_MATCH		=> 1133,
    UPDATE_INFO			=> 1134,
    CANT_CREATE_THREAD		=> 1135,
    WRONG_VALUE_COUNT_ON_ROW	=> 1136,
    CANT_REOPEN_TABLE		=> 1137,
    INVALID_USE_OF_NULL		=> 1138,
    REGEXP_ERROR		=> 1139,
    MIX_OF_GROUP_FUNC_AND_FIELDS=> 1140,
    NONEXISTING_GRANT		=> 1141,
    TABLEACCESS_DENIED_ERROR	=> 1142,
    COLUMNACCESS_DENIED_ERROR	=> 1143,
    ILLEGAL_GRANT_FOR_TABLE	=> 1144,
    GRANT_WRONG_HOST_OR_USER	=> 1145,
    NO_SUCH_TABLE		=> 1146,
    NONEXISTING_TABLE_GRANT	=> 1147,
    NOT_ALLOWED_COMMAND		=> 1148,
    SYNTAX_ERROR		=> 1149,
    DELAYED_CANT_CHANGE_LOCK	=> 1150,
    TOO_MANY_DELAYED_THREADS	=> 1151,
    ABORTING_CONNECTION		=> 1152,
    NET_PACKET_TOO_LARGE	=> 1153,
    NET_READ_ERROR_FROM_PIPE	=> 1154,
    NET_FCNTL_ERROR		=> 1155,
    NET_PACKETS_OUT_OF_ORDER	=> 1156,
    NET_UNCOMPRESS_ERROR	=> 1157,
    NET_READ_ERROR		=> 1158,
    NET_READ_INTERRUPTED	=> 1159,
    NET_ERROR_ON_WRITE		=> 1160,
    NET_WRITE_INTERRUPTED	=> 1161,
    TOO_LONG_STRING		=> 1162,
    TABLE_CANT_HANDLE_BLOB	=> 1163,
    TABLE_CANT_HANDLE_AUTO_INCREMENT	=> 1164,
    DELAYED_INSERT_TABLE_LOCKED	=> 1165,
    WRONG_COLUMN_NAME		=> 1166,
    WRONG_KEY_COLUMN		=> 1167,
    WRONG_MRG_TABLE		=> 1168,
    DUP_UNIQUE			=> 1169,
    BLOB_KEY_WITHOUT_LENGTH	=> 1170,
    PRIMARY_CANT_HAVE_NULL	=> 1171,
    TOO_MANY_ROWS		=> 1172,
    REQUIRES_PRIMARY_KEY	=> 1173,
    NO_RAID_COMPILED		=> 1174,
    UPDATE_WITHOUT_KEY_IN_SAFE_MODE	=> 1175,
    KEY_DOES_NOT_EXITS		=> 1176,
    CHECK_NO_SUCH_TABLE		=> 1177,
    CHECK_NOT_IMPLEMENTED	=> 1178,
    CANT_DO_THIS_DURING_AN_TRANSACTION	=> 1179,
    ERROR_DURING_COMMIT		=> 1180,
    ERROR_DURING_ROLLBACK	=> 1181,
    ERROR_DURING_FLUSH_LOGS	=> 1182,
    ERROR_DURING_CHECKPOINT	=> 1183,
    NEW_ABORTING_CONNECTION	=> 1184,
    DUMP_NOT_IMPLEMENTED	=> 1185,
    FLUSH_MASTER_BINLOG_CLOSED	=> 1186,
    INDEX_REBUILD		=> 1187,
    MASTER			=> 1188,
    MASTER_NET_READ		=> 1189,
    MASTER_NET_WRITE		=> 1190,
    FT_MATCHING_KEY_NOT_FOUND	=> 1191,
    LOCK_OR_ACTIVE_TRANSACTION	=> 1192,
    UNKNOWN_SYSTEM_VARIABLE	=> 1193,
    CRASHED_ON_USAGE		=> 1194,
    CRASHED_ON_REPAIR		=> 1195,
    WARNING_NOT_COMPLETE_ROLLBACK	=> 1196,
    TRANS_CACHE_FULL		=> 1197,
    SLAVE_MUST_STOP		=> 1198,
    SLAVE_NOT_RUNNING		=> 1199,
    BAD_SLAVE			=> 1200,
    MASTER_INFO			=> 1201,
    SLAVE_THREAD		=> 1202,
    TOO_MANY_USER_CONNECTIONS	=> 1203,
    SET_CONSTANTS_ONLY		=> 1204,
    LOCK_WAIT_TIMEOUT		=> 1205,
    LOCK_TABLE_FULL		=> 1206,
    READ_ONLY_TRANSACTION	=> 1207,
    DROP_DB_WITH_READ_LOCK	=> 1208,
    CREATE_DB_WITH_READ_LOCK	=> 1209,
    WRONG_ARGUMENTS		=> 1210,
    NO_PERMISSION_TO_CREATE_USER=> 1211,
    UNION_TABLES_IN_DIFFERENT_DIR	=> 1212,
    LOCK_DEADLOCK		=> 1213,
    TABLE_CANT_HANDLE_FULLTEXT	=> 1214,
    CANNOT_ADD_FOREIGN		=> 1215,
    NO_REFERENCED_ROW		=> 1216,
    ROW_IS_REFERENCED		=> 1217,
    CONNECT_TO_MASTER		=> 1218,
    QUERY_ON_MASTER		=> 1219,
    ERROR_WHEN_EXECUTING_COMMAND=> 1220,
    WRONG_USAGE			=> 1221,
    WRONG_NUMBER_OF_COLUMNS_IN_SELECT	=> 1222,
    CANT_UPDATE_WITH_READLOCK	=> 1223,
    MIXING_NOT_ALLOWED		=> 1224,
    DUP_ARGUMENT		=> 1225,
    USER_LIMIT_REACHED		=> 1226,
    SPECIFIC_ACCESS_DENIED_ERROR=> 1227,
    LOCAL_VARIABLE		=> 1228,
    GLOBAL_VARIABLE		=> 1229,
    NO_DEFAULT			=> 1230,
    WRONG_VALUE_FOR_VAR		=> 1231,
    WRONG_TYPE_FOR_VAR		=> 1232,
    VAR_CANT_BE_READ		=> 1233,
    CANT_USE_OPTION_HERE	=> 1234,
    NOT_SUPPORTED_YET		=> 1235,
    MASTER_FATAL_ERROR_READING_BINLOG	=> 1236,
    # only the slave SQL thread can be sent this
    SLAVE_IGNORED_TABLE		=> 1237, 
    INCORRECT_GLOBAL_LOCAL_VAR	=> 1238,
    ERROR_MESSAGES		=> 239,
};

1;
